# __       ___________    ____  _______  __       __       __  .__   __.   _______    .___________.  ______     ______    __          _______.
# |  |     |   ____\   \  /   / |   ____||  |     |  |     |  | |  \ |  |  /  _____|   |           | /  __  \   /  __  \  |  |        /       |
# |  |     |  |__   \   \/   /  |  |__   |  |     |  |     |  | |   \|  | |  |  __     `---|  |----`|  |  |  | |  |  |  | |  |       |   (----`
# |  |     |   __|   \      /   |   __|  |  |     |  |     |  | |  . `  | |  | |_ |        |  |     |  |  |  | |  |  |  | |  |        \   \
# |  `----.|  |____   \    /    |  |____ |  `----.|  `----.|  | |  |\   | |  |__| |        |  |     |  `--'  | |  `--'  | |  `----.----)   |
# |_______||_______|   \__/     |_______||_______||_______||__| |__| \__|  \______|        |__|      \______/   \______/  |_______|_______/
#
# By. github.com/chazza

format:
  pickaxe:
    name: "&e&lLEVELLING PICKAXE &8| &7LVL %level% &8|"
    lore:
      - "&8-------------------------------------"
      - "&7Mining helps level up your pickaxe,"
      - "&7rarer ores grant more experience."
      - ""
      - "&7Level: &6%level%"
      - "&7Blocks Mined: &6%mined%"
      - "&8-------------------------------------"
  axe:
    name: "&e&lLEVELLING AXE &8| &7LVL %level% &8|"
    lore:
      - "&8-------------------------------------"
      - "&7Mining helps level up your axe,"
      - "&7mine wood to grant more experience."
      - ""
      - "&7Level: &6%level%"
      - "&7Blocks Mined: &6%mined%"
      - "&8-------------------------------------"

settings:
  database:
    name: "levellingtools"
    host: "127.0.0.1"
    port: 27017
  blacklisted:
    world:
      - "example"
    region:
      - "blah"
message:
  not-your-omnitool: "&cSorry %player%, that omnitool is not yours."

level:
  1:
    settings:
      type: DIAMOND_PICKAXE
      xp: 0
      enchantments:
        EFFICIENCY: 1
      experience:
        COAL_ORE: 10
    commands:
      - "tm msg %player% &e&lLEVEL UP!;&7Your tool is now lvl &f%level%"

  2:
    settings:
      type: MEME_PICKAXE
      xp: 100
      enchantments:
        EFFICIENCY: 1
      experience:
        COAL_ORE: 10

    commands:
      - "tm msg %player% &e&lLEVEL UP!;&7Your tool is now lvl &f%level%"