# __       ___________    ____  _______  __       __       __  .__   __.   _______    .___________.  ______     ______    __          _______.
# |  |     |   ____\   \  /   / |   ____||  |     |  |     |  | |  \ |  |  /  _____|   |           | /  __  \   /  __  \  |  |        /       |
# |  |     |  |__   \   \/   /  |  |__   |  |     |  |     |  | |   \|  | |  |  __     `---|  |----`|  |  |  | |  |  |  | |  |       |   (----`
# |  |     |   __|   \      /   |   __|  |  |     |  |     |  | |  . `  | |  | |_ |        |  |     |  |  |  | |  |  |  | |  |        \   \
# |  `----.|  |____   \    /    |  |____ |  `----.|  `----.|  | |  |\   | |  |__| |        |  |     |  `--'  | |  `--'  | |  `----.----)   |
# |_______||_______|   \__/     |_______||_______||_______||__| |__| \__|  \______|        |__|      \______/   \______/  |_______|_______/
#
# By. github.com/chazza

settings:
  database:
    name: "levellingtools"
    host: "127.0.0.1"
    port: 27017
  format:
    pickaxe:
      name: "&e&lLEVELLING PICKAXE &8| &7LVL %level% &8| &7%broken% BLOCKS"
      lore:
        - "&8-------------------------------------"
        - "&7Mining helps level up your pickaxe,"
        - "&7rarer ores grant more experience."
        - ""
        - "&7Level: &6%level%"
        - "&7Blocks Mined: &6%broken%"
        - "&8-------------------------------------"
    axe:
      name: "&e&lLEVELLING AXE &8| &7LVL %level% &8| &7%broken% BLOCKS"
      lore:
        - "&8-------------------------------------"
        - "&7Mining helps level up your axe,"
        - "&7mine wood to grant more experience."
        - ""
        - "&7Level: &6%level%"
        - "&7Blocks Mined: &6%broken%"
        - "&8-------------------------------------"
    shovel:
      name: "&e&lLEVELLING SHOVEL &8| &7LVL %level% &8| &7%broken% BLOCKS"
      lore:
        - "&8-------------------------------------"
        - "&7Mining helps level up your shovel,"
        - "&7mine blocks to grant more experience."
        - ""
        - "&7Level: &6%level%"
        - "&7Blocks Mined: &6%broken%"
        - "&8-------------------------------------"

level:
  1:
    settings:
      type: IRON
      xp: -1
      format:
        pickaxe:
          name: ""
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
      experience:
        STONE: 25
        COAL_ORE: 10
    commands: []

  2:
    settings:
      type: GOLD
      xp: 100
      format:
        pickaxe:
          override: true
          name: "&b&lLEVELLING PICKAXE &8| &7LVL %level% &8| &7%broken% BLOCKS"
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
      experience:
        STONE: 25
        COAL_ORE: 10
    commands:
      - "tm msg %player% &e&lLEVEL UP!<nl>&7Tool is now level &f%level%"

  3:
    settings:
      type: DIAMOND
      xp: 200
      format:
        pickaxe:
          override: true
          name: "&c&lLEVELLING PICKAXE &8| &7LVL %level% &8| &7%broken% BLOCKS"
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
      experience:
        STONE: 25
        COAL_ORE: 10
    commands:
      - "tm msg %player% &e&lLEVEL UP!<nl>&7Tool is now level &f%level%"

  4:
    settings:
      type: DIAMOND
      xp: 300
      format:
        pickaxe:
          override: true
          name: "&d&lLEVELLING PICKAXE &8| &7LVL %level% &8| &7%broken% BLOCKS"
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
        FORTUNE: 5
      experience:
        COAL_ORE: 10
        STONE: 75
        STONE:3: 100
    commands:
      - "tm msg %player% &e&lLEVEL UP!<nl>&7Tool is now level &f%level%"