# __       ___________    ____  _______  __       __       __  .__   __.   _______    .___________.  ______     ______    __          _______.
# |  |     |   ____\   \  /   / |   ____||  |     |  |     |  | |  \ |  |  /  _____|   |           | /  __  \   /  __  \  |  |        /       |
# |  |     |  |__   \   \/   /  |  |__   |  |     |  |     |  | |   \|  | |  |  __     `---|  |----`|  |  |  | |  |  |  | |  |       |   (----`
# |  |     |   __|   \      /   |   __|  |  |     |  |     |  | |  . `  | |  | |_ |        |  |     |  |  |  | |  |  |  | |  |        \   \
# |  `----.|  |____   \    /    |  |____ |  `----.|  `----.|  | |  |\   | |  |__| |        |  |     |  `--'  | |  `--'  | |  `----.----)   |
# |_______||_______|   \__/     |_______||_______||_______||__| |__| \__|  \______|        |__|      \______/   \______/  |_______|_______/
#

settings:

  # Enter your mongodb credentials here.
  database:
    name: "levellingtools"
    host: "127.0.0.1"
    port: 27017

  # You may blacklist a world or region, which will stop
  # players from being able to level up their tool.
  blacklist:
    world:
      # Enabling the cancel option will stop the block being
      # placed, or disabling will allow but not add xp.
      cancel: true
      list: []
    region:
      cancel: true
      # If you wish to enable these, add them below.
      # To disable change it to 'list: []'
      list:
        - 'a_bad_region'

  global:
    multiplier:
      test: 1.2

    xp:
      STONE: 1

    actions:
      - 'tm msg {player} &e&lLEVEL UP!<nl>&7Tool is now level &f{level}'
      - 'msg {player} &6[&eTool&6] &7You''ve reached level &f%level% with &e%blocks% &7block(s) broken. Congrats!'

# You can specify the default format for the tools,
# which may be overridden inside of the 'level' section.
# Placeholders: {level} (current tool level), {blocks} (total blocks broken)
format:
  pickaxe:
    name: "&e&lLEVELLING PICKAXE &8| &7LVL {level} &8| &7{blocks} BLOCKS"
    lore:
      - "&8-------------------------------------"
      - "&7Mining helps level up your pickaxe,"
      - "&7rarer ores grant more experience."
      - ""
      - "&7Level: &6{level}"
      - "&7Blocks Mined: &6{blocks}"
      - "&8-------------------------------------"
  axe:
    name: "&e&lLEVELLING AXE &8| &7LVL {level} &8| &7{blocks} BLOCKS"
    lore:
      - "&8-------------------------------------"
      - "&7Mining helps level up your axe,"
      - "&7mine wood to grant more experience."
      - ""
      - "&7Level: &6{level}"
      - "&7Blocks Mined: &6{blocks}"
      - "&8-------------------------------------"
  shovel:
    name: "&e&lLEVELLING SHOVEL &8| &7LVL {level} &8| &7{blocks} BLOCKS"
    lore:
      - "&8-------------------------------------"
      - "&7Mining helps level up your shovel,"
      - "&7mine blocks to grant more experience."
      - ""
      - "&7Level: &6{level}"
      - "&7Blocks Mined: &6{blocks}"
      - "&8-------------------------------------"

# This is the primary section, where you define
# your tools levels, alongside its enchantments.
level:
  1:
    settings:
      # This is the type of tool you wish to use.
      # Types: WOOD, STONE, IRON, GOLD and DIAMOND.
      type: IRON
      # The experience required to level up.
      # This only applies to level 2 and above.
      xp: -1
      # You may override the name and lore by specifying
      # it below, or setting it to 'name: ""' and 'lore: []'
      # to use the default (or previous level).
      format:
        pickaxe:
          name: ""
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      # The enchantments you wish to set onto the tool.
      # For example, 'EFFICIENCY', 'FORTUNE', 'UNBREAKING' etc.
      enchantments:
        # Format is '<ENCHANT>:<LEVEL>'
        EFFICIENCY: 1
      # The xp a player will gain from mining the listed block.
      experience:
        # Format is '<BLOCK>:<XP>'
        STONE: 25
        COAL_ORE: 10
    # These are the commands that are executed on level up.
    # You may ignore the below, and configure it for level 2+.
    actions: []

  2:
    settings:
      type: GOLD
      xp: 100
      format:
        pickaxe:
          override: true
          name: "&b&lLEVELLING PICKAXE &8| &7LVL {level} &8| &7{blocks} BLOCKS"
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
      experience:
        STONE: 25
        COAL_ORE: 10
    actions:
      - "tm msg {player} &e&lLEVEL UP!<nl>&7Tool is now level &f{level}"

  3:
    settings:
      type: DIAMOND
      xp: 200
      format:
        pickaxe:
          override: true
          name: "&c&lLEVELLING PICKAXE &8| &7LVL {level} &8| &7{blocks} BLOCKS"
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
      experience:
        STONE: 25
        COAL_ORE: 10
    actions:
      - "tm msg {player} &e&lLEVEL UP!<nl>&7Tool is now level &f{level}"

  4:
    settings:
      type: DIAMOND
      xp: 300
      format:
        pickaxe:
          override: true
          name: "&d&lLEVELLING PICKAXE &8| &7LVL {level} &8| &7{blocks} BLOCKS"
          lore: []
        axe:
          name: ""
          lore: []
        shovel:
          name: ""
          lore: []
      enchantments:
        EFFICIENCY: 1
        FORTUNE: 5
      experience:
        COAL_ORE: 10
        STONE: 75
        STONE:3: 100
    actions:
      - "tm msg {player} &e&lLEVEL UP!<nl>&7Tool is now level &f{level}"