name: ${plugin}
version: ${project.version}
main: ${package}
author: Chazza
website: https://plugins.gg/
softdepend: ["PlaceholderAPI", "WorldGuard"]

commands:
  levellingtools:
    description: LevellingTools commands
    usage: ""
    aliases: ["ltools", "tools", "tool", "lt"]

permissions:
  ltools.reload:
    description: Reload the configuration file into memory
  ltools.info:
    description: View information about the plugin
    default: true
  ltools.xp:
    description: View yourself or another players xp amount
    default: true
  ltools.help:
    description: View commands you have access to within the plugin
    default: true